### ISSUE TITLE
icons and functionality required its not working.

### ISSUE THREAD

**Issue by Kira6381** [Zrital3265/Zaskify#1]
![image](https://github.com/Zrital3265/Zaskify/assets/144708870/5f6fa5e9-36ab-4b9c-a50a-f0e4f13b5683)
it doesnt work. assign me this thing so that i can make it happen please.

**Comment by Zrital3265** [comment]
> ![image](https://private-user-images.githubusercontent.com/144708870/321504894-5f6fa5e9-36ab-4b9c-a50a-f0e4f13b5683.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTI4MTA3MTksIm5iZiI6MTcxMjgxMDQxOSwicGF0aCI6Ii8xNDQ3MDg4NzAvMzIxNTA0ODk0LTVmNmZhNWU5LTM2YWItNGI5Yy1hNTBhLWYwZTRmMTNiNTY4My5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQxMVQwNDQwMTlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0yYWViZTMxZWFkMjIyM2RlNTE1NjU5OWEzMjg0YmFlMWQ3NzM5YWQ5NWYzNTAyZmJjMTFiZWY2ZjJmZWNiZmQ3JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.YiLDjZaHtzRFDs15jI0DxVARzzn0TVbIg9kzITXIIyo) it doesnt work. assign me this thing so that i can make it happen please.

you have been assigned work on it, thanks.
