### ISSUE TITLE
Drag and drop feat required.

### ISSUE THREAD

**Issue by Zrital3265** [Zrital3265/Zaskify#6]
Add the drag and drop feature in between completed task and current task thanks.

**Comment by Kira6381** [comment]
Woking on it get it done by 4 PM.

**Comment by harunugurlu** [comment]
Hello, I want to work on this, could you provide details, such as wdym by "drag and drop between completed and current tasks"? My understanding is that we need to be able to drag a current task from the current column to the completed column.

**Comment by Zrital3265** [comment]
> Hello, I want to work on this, could you provide details, such as wdym by "drag and drop between completed and current tasks"? My understanding is that we need to be able to drag a current task from the current column to the completed column.

Hey mate thank you for your interest. I just meant the basic drag-and-drop feature which lets you drag the active task into completed tasks, the easiest way might be using some external packages like react-beautiful-dnd.

**Comment by Kira6381** [comment]
Hey just to let you guys know i am almost done with styling and drag and drop part just gonna take like 45min to do so. Just informing you guys so that no one has to waste their time.

**Comment by Zrital3265** [comment]
Thankks @Kira6381 .

**Comment by harunugurlu** [comment]
@Kira6381 Hey, I just reviewed your work and it is very well done. I only noticed a minor bug, when we drag a task from todo to completed, it is not being marked as done (not being  ̶s̶t̶r̶i̶k̶e̶t̶h̶r̶o̶u̶g̶h̶). I have fixed it and we can merge it if you want @Zrital3265
